import streamlit as st
from ai.promptbuilder import build_prompt
from ai.llm import generate_ai_response
from utils.formatter import clean_response
from document.pdf_generator import generate_pdf

st.set_page_config(page_title="InsightsDraft", page_icon="🤖", layout="wide")

st.title("InsightsDraft")
st.caption("Transform rough notes into submission ready documents with AI.")

st.divider()

topic=st.text_input("Topic", placeholder="Enter your topic....")

document_type=st.selectbox("Document Type",["Assignment","Research Summary","Meeting Minutes","Business Report","Study Notes"])

writing_style=st.selectbox("Writing Style",["Academic","Professional","Technical","Simple","Creative"])

output_length=st.selectbox("Output Length",["Short","Medium","Long"])

notes=st.text_area("Paste Your Notes", height=250, placeholder="Paste your rough notes here....")

st.write(f"Character Count: {len(notes)}")
if "document" not in st.session_state:
    st.session_state.document = None
generate=st.button("Generate Draft", use_container_width=True)

if generate:
    if not topic or not document_type or not writing_style or not output_length or not notes:
        st.warning("Please fill in all the fields before generating the document.")
        st.stop()
    prompt=build_prompt(topic,document_type,writing_style,output_length,notes)
    with st.spinner("Generating your draft..."):
        document=generate_ai_response(prompt)
        st.success("Draft generated successfully!")
        st.markdown("---")
        document = clean_response(document)
        st.session_state.document = document

if st.session_state.document:
    edited_document=st.text_area("Edit Your Document", value=st.session_state.document, height=500)
    st.divider()
    st.markdown("## Document Settings")
    file_name = st.text_input("File Name",value=topic.replace(" ", "_"))
    cover_page=st.checkbox("Include Cover Page", value=False)
    date=st.checkbox("Include Date", value=False)
    if date:
        date_value = st.date_input("Select Date")
    author=st.checkbox("Include Author Name", value=False)
    if author:
        author_name = st.text_input("Enter Author Name")
    inst_comp=st.checkbox("Include Institution/Company Name", value=False)
    if inst_comp:
        inst_comp_name = st.text_input("Enter Institution/Company Name")
    footer=st.checkbox("Include Footer", value=False)
    if footer:
        footer_text = st.text_input("Customize the Footer Text",value="Generated by InsightsDraft AI")
    toc=st.checkbox("Include Table of Contents", value=False)
    page=st.checkbox("Include Page Numbers", value=False)
    ref=st.checkbox("Include References Section", value=False)
    theme=st.selectbox("Select Theme",["Professional","Creative","Minimalist","Academic","Modern","Corporate"])

    st.divider()
    st.markdown("## Export")
    export_pdf=st.button("Generate PDF")
    settings={
        "title": topic.title(),
        "document_type": document_type,
        "cover_page": cover_page,
        "date_value": str(date_value) if date else None,
        "author_name": author_name if author else None,
        "inst_comp_name": inst_comp_name if inst_comp else None,
        "footer_text": footer_text if footer else None,
        "toc": toc,
        "page": page,
        "ref": ref,
        "theme": theme
    }
    if export_pdf:
        generate_pdf(f"outputs/{file_name}.pdf", edited_document, settings)
        st.success(f"PDF generated successfully! (./{file_name}.pdf).")

        with open(f"outputs/{file_name}.pdf", "rb") as pdf_file:
            st.download_button(label="Download PDF",data=pdf_file,file_name=f"{file_name}.pdf",mime="application/pdf")